version: "2"

run:
  timeout: 10m

linters:
  default: none

formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/zitadel/terraform-provider-zitadel/v2)
