package application_oidc

const (
	AppIDVar                    = "app_id"
	appIDsVar                   = "app_ids"
	ProjectIDVar                = "project_id"
	NameVar                     = "name"
	nameMethodVar               = "name_method"
	redirectURIsVar             = "redirect_uris"
	responseTypesVar            = "response_types"
	grantTypesVar               = "grant_types"
	appTypeVar                  = "app_type"
	authMethodTypeVar           = "auth_method_type"
	postLogoutRedirectURIsVar   = "post_logout_redirect_uris"
	versionVar                  = "version"
	devModeVar                  = "dev_mode"
	accessTokenTypeVar          = "access_token_type"
	accessTokenRoleAssertionVar = "access_token_role_assertion"
	idTokenRoleAssertionVar     = "id_token_role_assertion"
	idTokenUserinfoAssertionVar = "id_token_userinfo_assertion"
	clockSkewVar                = "clock_skew"
	additionalOriginsVar        = "additional_origins"
	ClientIDVar                 = "client_id"
	ClientSecretVar             = "client_secret"
)
