package idp_utils

import (
	"github.com/hashicorp/go-cty/cty"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/zitadel/zitadel-go/v3/pkg/client/zitadel/idp"
	"github.com/zitadel/zitadel-go/v3/pkg/client/zitadel/object"

	"github.com/zitadel/terraform-provider-zitadel/v2/zitadel/helper"
)

const (
	IdpIDVar             = "id"
	NameVar              = "name"
	ClientIDVar          = "client_id"
	ClientSecretVar      = "client_secret"
	ClientSecretHashVar  = "client_secret_hash"
	ScopesVar            = "scopes"
	IsLinkingAllowedVar  = "is_linking_allowed"
	IsCreationAllowedVar = "is_creation_allowed"
	IsAutoCreationVar    = "is_auto_creation"
	IsAutoUpdateVar      = "is_auto_update"
	AutoLinkingVar       = "auto_linking"
	NameMethodVar        = "name_method"
	TypeVar              = "type"
	StateVar             = "state"
	OwnerTypeVar         = "owner_type"
	IdpsVar              = "idps"
)

var (
	NameFilterDataSourceField = &schema.Schema{
		Type:        schema.TypeString,
		Optional:    true,
		Description: "Name to filter identity providers by",
	}
	NameMethodDataSourceField = &schema.Schema{
		Type:        schema.TypeString,
		Optional:    true,
		Description: "Method for querying identity providers by name" + helper.DescriptionEnumValuesList(object.TextQueryMethod_name),
		ValidateDiagFunc: func(value interface{}, path cty.Path) diag.Diagnostics {
			return helper.EnumValueValidation(NameMethodVar, value, object.TextQueryMethod_value)
		},
		Default: object.TextQueryMethod_TEXT_QUERY_METHOD_EQUALS_IGNORE_CASE.String(),
	}
	TypeFilterDataSourceField = &schema.Schema{
		Type:        schema.TypeString,
		Optional:    true,
		Description: "Type to filter identity providers by, PROVIDER_TYPE_UNSPECIFIED applies no filter" + helper.DescriptionEnumValuesList(idp.ProviderType_name),
		ValidateDiagFunc: func(value interface{}, path cty.Path) diag.Diagnostics {
			return helper.EnumValueValidation(TypeVar, value, idp.ProviderType_value)
		},
	}
	OwnerTypeFilterDataSourceField = &schema.Schema{
		Type:        schema.TypeString,
		Optional:    true,
		Description: "Owner type to filter identity providers by, either the instance (system) or the organization, IDP_OWNER_TYPE_UNSPECIFIED applies no filter" + helper.DescriptionEnumValuesList(idp.IDPOwnerType_name),
		ValidateDiagFunc: func(value interface{}, path cty.Path) diag.Diagnostics {
			return helper.EnumValueValidation(OwnerTypeVar, value, idp.IDPOwnerType_value)
		},
	}
	IdpsDataSourceField = &schema.Schema{
		Type:        schema.TypeList,
		Computed:    true,
		Description: "List of identity providers",
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				IdpIDVar: {
					Type:        schema.TypeString,
					Computed:    true,
					Description: "ID of the identity provider",
				},
				NameVar: {
					Type:        schema.TypeString,
					Computed:    true,
					Description: "Name of the identity provider",
				},
				TypeVar: {
					Type:        schema.TypeString,
					Computed:    true,
					Description: "Type of the identity provider",
				},
				StateVar: {
					Type:        schema.TypeString,
					Computed:    true,
					Description: "State of the identity provider",
				},
				OwnerTypeVar: {
					Type:        schema.TypeString,
					Computed:    true,
					Description: "Owner type of the identity provider, either the instance (system) or an organization",
				},
			},
		},
	}
	IdPIDDataSourceField = &schema.Schema{
		Type:        schema.TypeString,
		Required:    true,
		Description: "The ID of this resource.",
	}
	NameResourceField = &schema.Schema{
		Type:        schema.TypeString,
		Optional:    true,
		Description: "Name of the IDP",
	}
	NameDataSourceField = &schema.Schema{
		Type:        schema.TypeString,
		Computed:    true,
		Description: "Name of the IDP",
	}
	ClientIDResourceField = &schema.Schema{
		Type:        schema.TypeString,
		Required:    true,
		Description: "client id generated by the identity provider",
	}
	ClientIDDataSourceField = &schema.Schema{
		Type:        schema.TypeString,
		Computed:    true,
		Description: "client id generated by the identity provider",
	}
	ClientSecretResourceField = &schema.Schema{
		Type:        schema.TypeString,
		Required:    true,
		Description: "client secret generated by the identity provider. This value is write-only and is never stored in Terraform state; it cannot be read back or retrieved from a datasource.",
		Sensitive:   true,
		WriteOnly:   true,
	}
	ClientSecretHashResourceField = &schema.Schema{
		Type:        schema.TypeString,
		Computed:    true,
		Sensitive:   true,
		Description: "A non-reversible hash of the write-only client_secret, used to detect when the secret changes. It does not contain the secret itself.",
	}
	ScopesResourceField = &schema.Schema{
		Type: schema.TypeSet,
		Elem: &schema.Schema{
			Type: schema.TypeString,
		},
		Optional:    true,
		Description: "the scopes requested by ZITADEL during the request on the identity provider",
	}
	ScopesDataSourceField = &schema.Schema{
		Type: schema.TypeSet,
		Elem: &schema.Schema{
			Type: schema.TypeString,
		},
		Computed:    true,
		Description: "the scopes requested by ZITADEL during the request on the identity provider",
	}
	IsLinkingAllowedResourceField = &schema.Schema{
		Type:        schema.TypeBool,
		Required:    true,
		Description: "enable if users should be able to link an existing ZITADEL user with an external account",
	}
	IsLinkingAllowedDataSourceField = &schema.Schema{
		Type:        schema.TypeBool,
		Computed:    true,
		Description: "enabled if users are able to link an existing ZITADEL user with an external account",
	}
	IsCreationAllowedResourceField = &schema.Schema{
		Type:        schema.TypeBool,
		Required:    true,
		Description: "enable if users should be able to create a new account in ZITADEL when using an external account",
	}
	IsCreationAllowedDataSourceField = &schema.Schema{
		Type:        schema.TypeBool,
		Computed:    true,
		Description: "enabled if users are able to create a new account in ZITADEL when using an external account",
	}
	IsAutoCreationResourceField = &schema.Schema{
		Type:        schema.TypeBool,
		Required:    true,
		Description: "enable if a new account in ZITADEL should be created automatically on login with an external account",
	}
	IsAutoCreationDataSourceField = &schema.Schema{
		Type:        schema.TypeBool,
		Computed:    true,
		Description: "enabled if a new account in ZITADEL are created automatically on login with an external account",
	}
	IsAutoUpdateResourceField = &schema.Schema{
		Type:        schema.TypeBool,
		Required:    true,
		Description: "enable if a the ZITADEL account fields should be updated automatically on each login",
	}
	IsAutoUpdateDataSourceField = &schema.Schema{
		Type:        schema.TypeBool,
		Computed:    true,
		Description: "enabled if a the ZITADEL account fields are updated automatically on each login",
	}
	AutoLinkingResourceField = &schema.Schema{
		Type:        schema.TypeString,
		Optional:    true,
		Description: "Enable if users should get prompted to link an existing ZITADEL user to an external account if the selected attribute matches" + helper.DescriptionEnumValuesList(idp.AutoLinkingOption_name),
		ValidateDiagFunc: func(value interface{}, path cty.Path) diag.Diagnostics {
			return helper.EnumValueValidation(AutoLinkingVar, value, idp.AutoLinkingOption_value)
		},
		Default: idp.AutoLinkingOption_name[0],
	}
	AutoLinkingDataSourceField = &schema.Schema{
		Type:        schema.TypeString,
		Computed:    true,
		Description: "Enable if users should get prompted to link an existing ZITADEL user to an external account if the selected attribute matches" + helper.DescriptionEnumValuesList(idp.AutoLinkingOption_name),
	}
)
